"""init

Revision ID: 534173d1cc0c
Revises:
Create Date: 2026-06-08 11:17:37.552403

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "534173d1cc0c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "silver_rates",
        sa.Column("object_key", sa.String(), nullable=False),
        sa.Column("rates_timestamp", sa.Date(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("silver_rates_pkey")),
        sa.UniqueConstraint("object_key", name=op.f("silver_rates_object_key_key")),
    )
    op.create_index(op.f("silver_rates_id_idx"), "silver_rates", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("silver_rates_id_idx"), table_name="silver_rates")
    op.drop_table("silver_rates")
    # ### end Alembic commands ###
