"""Add golden layer

Revision ID: 748bef9904c6
Revises: 534173d1cc0c
Create Date: 2026-06-08 15:34:26.116691

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "748bef9904c6"
down_revision: Union[str, Sequence[str], None] = "534173d1cc0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "golden_rates",
        sa.Column("rate_date", sa.Date(), nullable=False),
        sa.Column("num_code", sa.String(), nullable=False),
        sa.Column("char_code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("rate", sa.Numeric(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("golden_rates_pkey")),
        sa.UniqueConstraint(
            "rate_date", "char_code", name="uq_golden_rates_date_currency"
        ),
    )
    op.create_index(
        op.f("golden_rates_char_code_idx"), "golden_rates", ["char_code"], unique=False
    )
    op.create_index(op.f("golden_rates_id_idx"), "golden_rates", ["id"], unique=False)
    op.create_index(
        op.f("golden_rates_rate_date_idx"), "golden_rates", ["rate_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("golden_rates_rate_date_idx"), table_name="golden_rates")
    op.drop_index(op.f("golden_rates_id_idx"), table_name="golden_rates")
    op.drop_index(op.f("golden_rates_char_code_idx"), table_name="golden_rates")
    op.drop_table("golden_rates")
    # ### end Alembic commands ###
